#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_CCW_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_CCW_HPP_INCLUDED

#include "ccw_result.hpp"
#include "ccw_points.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_CCW_HPP_INCLUDED
