#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_CONVEX_POLYGON_DIAMETER_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_CONVEX_POLYGON_DIAMETER_HPP_INCLUDED

#include "convex_polygon_diameter_result.hpp"
#include "convex_polygon_diameter_normalized.hpp"
#include "convex_polygon_diameter_points.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_CONVEX_POLYGON_DIAMETER_HPP_INCLUDED
