#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_EAR_CLIPPING_TRIANGLE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_EAR_CLIPPING_TRIANGLE_HPP_INCLUDED

#include <array>
#include <cstddef>

using EarClippingTriangle = std::array<std::size_t, 3>;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_EAR_CLIPPING_TRIANGLE_HPP_INCLUDED
