#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_ORTHOGONAL_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_ORTHOGONAL_HPP_INCLUDED

#include "orthogonal_lines.hpp"
#include "orthogonal_vectors.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_ORTHOGONAL_HPP_INCLUDED
