#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_PARALLEL_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_PARALLEL_HPP_INCLUDED

#include "parallel_lines.hpp"
#include "parallel_vectors.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_PARALLEL_HPP_INCLUDED
