#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_POLYGON_BOUNDARY_POINTS_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_POLYGON_BOUNDARY_POINTS_HPP_INCLUDED

#include "polygon_boundary_points/enumerate_points_on_polygon_boundary.hpp"
#include "polygon_boundary_points/polygon_boundary_point_query.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_POLYGON_BOUNDARY_POINTS_HPP_INCLUDED
