#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_SEGMENT_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_SEGMENT_HPP_INCLUDED

#include "segment_type.hpp"
#include "supporting_line_segment.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_SEGMENT_HPP_INCLUDED
