#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_CIRCLE3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_CIRCLE3_HPP_INCLUDED

#include "point3.hpp"

struct Circle3{
    Point3 center;
    Point3 normal;
    long double radius;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_CIRCLE3_HPP_INCLUDED
