#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_PLANE3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_PLANE3_HPP_INCLUDED

#include "point3.hpp"

struct Plane3{
    Point3 point;
    Point3 normal;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_PLANE3_HPP_INCLUDED
