#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_PLANE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_PLANE_HPP_INCLUDED

#include "../../aggregate/all/geometry_primitives.hpp"

using Plane = Plane3;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_PLANE_HPP_INCLUDED
