#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_POLYGON3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_POLYGON3_HPP_INCLUDED

#include <vector>

#include "../../aggregate/all/geometry_primitives.hpp"

using Polygon3 = std::vector<Point3>;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_POLYGON3_HPP_INCLUDED
