#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_SEGMENT3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_SEGMENT3_HPP_INCLUDED

#include "point3.hpp"

struct Segment3{
    Point3 a;
    Point3 b;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_SEGMENT3_HPP_INCLUDED
