#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_TRIANGLE3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_TRIANGLE3_HPP_INCLUDED

#include "point3.hpp"

struct Triangle3{
    Point3 a;
    Point3 b;
    Point3 c;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_TRIANGLE3_HPP_INCLUDED
