#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_VECTOR3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_VECTOR3_HPP_INCLUDED

#include "../../aggregate/all/geometry_primitives.hpp"

using Vector3 = Point3;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_TYPE_DEFINITION_VECTOR3_HPP_INCLUDED
