#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_GEOMETRY_INTEGER_WIDE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_GEOMETRY_INTEGER_WIDE_HPP_INCLUDED

#include "../../../../math/integer/exact_integer.hpp"

using GeometryIntegerWide = ExactInteger;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_GEOMETRY_INTEGER_WIDE_HPP_INCLUDED
