#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_SEGMENT_TYPE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_SEGMENT_TYPE_HPP_INCLUDED

#include "point.hpp"

struct Segment {
    Point a;
    Point b;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_SEGMENT_TYPE_HPP_INCLUDED
