#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_VISIBILITY_GRAPH_EDGE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_VISIBILITY_GRAPH_EDGE_HPP_INCLUDED

#include <cstddef>

struct VisibilityGraphEdge{
    std::size_t first;
    std::size_t second;
    long double distance;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_VISIBILITY_GRAPH_EDGE_HPP_INCLUDED
