#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_VORONOI_EDGE_KIND_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_VORONOI_EDGE_KIND_HPP_INCLUDED

enum class VoronoiEdgeKind{
    SEGMENT,
    RAY,
    LINE,
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_VORONOI_EDGE_KIND_HPP_INCLUDED
