#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_WEIGHTED_POINT_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_WEIGHTED_POINT_HPP_INCLUDED

#include "point.hpp"

struct WeightedPoint{
    Point point;
    long double weight;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_TYPE_DEFINITION_WEIGHTED_POINT_HPP_INCLUDED
