#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_LINE_LINE_SEGMENT_SKEW_SEGMENT_LINE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_LINE_LINE_SEGMENT_SKEW_SEGMENT_LINE_HPP_INCLUDED

#include "../line_segment/line_segment_skew_line_segment.hpp"

inline bool skew(const Segment3& first, const Line3& second){
    return skew(second, first);
}

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_LINE_LINE_SEGMENT_SKEW_SEGMENT_LINE_HPP_INCLUDED
