#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_LINE_LINE_SEGMENT_OVERLAP_SEGMENT_LINE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_LINE_LINE_SEGMENT_OVERLAP_SEGMENT_LINE_HPP_INCLUDED

#include "../line_segment/line_segment_overlap_line_segment.hpp"

inline bool overlap(const Segment3& first, const Line3& second){
    return overlap(second, first);
}

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_LINE_LINE_SEGMENT_OVERLAP_SEGMENT_LINE_HPP_INCLUDED
