#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SCALAR_PLANE_LINE_LINE_PLANE_DISTANCE_PLANE_LINE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SCALAR_PLANE_LINE_LINE_PLANE_DISTANCE_PLANE_LINE_HPP_INCLUDED

#include "../line_plane/line_plane_distance_line_plane.hpp"

inline long double distance(const Plane3& plane, const Line3& line){
    return distance(line, plane);
}

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SCALAR_PLANE_LINE_LINE_PLANE_DISTANCE_PLANE_LINE_HPP_INCLUDED
