#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_RAY_LINE_LINE_RAY_SKEW_RAY_LINE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_RAY_LINE_LINE_RAY_SKEW_RAY_LINE_HPP_INCLUDED

#include "../line_ray/line_ray_skew_line_ray.hpp"

inline bool skew(const Ray3& first, const Line3& second){
    return skew(second, first);
}

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_RAY_LINE_LINE_RAY_SKEW_RAY_LINE_HPP_INCLUDED
