#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SCALAR_LONG_DOUBLE_IS_FINITE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SCALAR_LONG_DOUBLE_IS_FINITE_HPP_INCLUDED

#include <cmath>

inline bool geometry3d_is_finite(long double value) noexcept{
    return std::isfinite(value);
}

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SCALAR_LONG_DOUBLE_IS_FINITE_HPP_INCLUDED
