#!/usr/bin/env python3

from __future__ import annotations

import json
import tempfile
import unittest
from pathlib import Path

import yaml

import check_generated_docs_index as checker


class GeneratedDocsIndexTest(unittest.TestCase):
    def make_fixture(self, directory: Path, *, create_target: bool = True) -> tuple[Path, Path]:
        test_path = "test/standalone/example.test.cpp"
        front_matter = {
            "data": {
                "top": [
                    {"type": "Library Files", "categories": []},
                    {
                        "type": "Verification Files",
                        "categories": [
                            {
                                "name": "test/onlinejudge/",
                                "pages": [],
                            },
                            {
                                "name": "test/standalone/",
                                "pages": [{"path": test_path, "icon": "warning"}],
                            },
                        ],
                    },
                ]
            }
        }
        index = directory / "index.md"
        index.write_text(
            "---\n"
            + yaml.safe_dump(front_matter, sort_keys=False)
            + "---\nGenerated by competitive-verifier.\n",
            encoding="utf-8",
        )
        plan = directory / "verify-files.json"
        plan.write_text(
            json.dumps({"files": {test_path: {"verification": []}}}),
            encoding="utf-8",
        )
        if create_target:
            target = directory / f"{test_path}.md"
            target.parent.mkdir(parents=True)
            target.write_text("generated page\n", encoding="utf-8")
        return index, plan

    def test_accepts_visible_standalone_entry_with_link_target(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            index, plan = self.make_fixture(Path(temporary))
            checker.validate_generated_index(index, plan)

    def test_rejects_standalone_entry_outside_verification_files(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            root = Path(temporary)
            index, plan = self.make_fixture(root)
            text = index.read_text(encoding="utf-8")
            text = text.replace("type: Verification Files", "type: Library Files")
            index.write_text(text, encoding="utf-8")
            with self.assertRaisesRegex(checker.GeneratedIndexError, "Verification Files"):
                checker.validate_generated_index(index, plan)

    def test_rejects_broken_standalone_link_target(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            index, plan = self.make_fixture(Path(temporary), create_target=False)
            with self.assertRaisesRegex(checker.GeneratedIndexError, "link targets"):
                checker.validate_generated_index(index, plan)

    def test_rejects_plan_without_standalone_tests(self) -> None:
        with tempfile.TemporaryDirectory() as temporary:
            index, plan = self.make_fixture(Path(temporary))
            plan.write_text(json.dumps({"files": {}}), encoding="utf-8")
            with self.assertRaisesRegex(checker.GeneratedIndexError, "no standalone"):
                checker.validate_generated_index(index, plan)


if __name__ == "__main__":
    unittest.main()
