#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_CLOSEST_PAIR_INDICES_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_CLOSEST_PAIR_INDICES_HPP_INCLUDED

#include "../../type/definition/closest_pair_result.hpp"
#include "../../result/point_set/closest_pair_indices_points.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_CLOSEST_PAIR_INDICES_HPP_INCLUDED
