#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_DELAUNAY_TRIANGULATION_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_DELAUNAY_TRIANGULATION_HPP_INCLUDED

#include "../../type/definition/delaunay_triangulation_result.hpp"
#include "../../result/point_set/delaunay_triangulation_points.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_DELAUNAY_TRIANGULATION_HPP_INCLUDED
