#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_EAR_CLIPPING_TRIANGULATION_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_EAR_CLIPPING_TRIANGULATION_HPP_INCLUDED

#include "../../type/definition/ear_clipping_triangle.hpp"
#include "../../triangle/point_set/ear_clipping_triangulation_points.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_EAR_CLIPPING_TRIANGULATION_HPP_INCLUDED
