#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_GEOMETRY_SCALED_SIGN_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_GEOMETRY_SCALED_SIGN_HPP_INCLUDED

#include "../../integer/scalar/geometry_scaled_sign_value_tolerance_roundoff_scales.hpp"
#include "../../integer/scalar/geometry_scaled_sign_value_scale.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_GEOMETRY_SCALED_SIGN_HPP_INCLUDED
