#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_GEOMETRY_SIGN_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_GEOMETRY_SIGN_HPP_INCLUDED

#include "../../integer/scalar/geometry_absolute_sign.hpp"
#include "geometry_scaled_sign.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_GEOMETRY_SIGN_HPP_INCLUDED
