#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_NORMALIZED_LINE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_NORMALIZED_LINE_HPP_INCLUDED

#include "../../type/definition/normalized_line_result.hpp"
#include "../../line/line/normalized_line_line.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_NORMALIZED_LINE_HPP_INCLUDED
