#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_SEGMENT_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_SEGMENT_HPP_INCLUDED

#include "../../type/definition/segment_type.hpp"
#include "../../line/segment/supporting_line_segment.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_2D_AGGREGATE_ALL_SEGMENT_HPP_INCLUDED
