#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_CENTROID_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_CENTROID_HPP_INCLUDED

#include "tetrahedron_centroid.hpp"
#include "triangle_centroid.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_CENTROID_HPP_INCLUDED
