#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_INTEGER_POINT3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_INTEGER_POINT3_HPP_INCLUDED

#include <array>
#include <cstdint>

using IntegerPoint3 = std::array<std::int64_t, 3>;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_INTEGER_POINT3_HPP_INCLUDED
