#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PLANE_PLANE_COMMON_INTERSECTION_RESULT3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PLANE_PLANE_COMMON_INTERSECTION_RESULT3_HPP_INCLUDED

#include <variant>

#include "geometry_primitives.hpp"

using PlanePlaneIntersection3 = std::variant<std::monostate, Line3, Plane3>;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PLANE_PLANE_COMMON_INTERSECTION_RESULT3_HPP_INCLUDED
