#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PLANE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PLANE_HPP_INCLUDED

#include "base.hpp"

using Plane = Plane3;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PLANE_HPP_INCLUDED
