#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_POLYGON3_TO_2D_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_POLYGON3_TO_2D_HPP_INCLUDED

#include "polygon3_to_2d_with_plane_coordinate_system.hpp"
#include "polygon3_to_2d_without_plane_coordinate_system.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_POLYGON3_TO_2D_HPP_INCLUDED
