#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_QUATERNION3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_QUATERNION3_HPP_INCLUDED

#include "quaternion3_type.hpp"
#include "quaternion3_dot.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_QUATERNION3_HPP_INCLUDED
