#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SPHERE3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SPHERE3_HPP_INCLUDED

#include "point3.hpp"

struct Sphere3{
    Point3 center;
    long double radius;
};

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SPHERE3_HPP_INCLUDED
