#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SPHERE_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SPHERE_HPP_INCLUDED

#include "base.hpp"

using Sphere = Sphere3;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_SPHERE_HPP_INCLUDED
