#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_VECTOR3_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_VECTOR3_HPP_INCLUDED

#include "base.hpp"

using Vector3 = Point3;

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_VECTOR3_HPP_INCLUDED
