#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_RAY_RAY_SEGMENT_SKEW_SEGMENT_RAY_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_RAY_RAY_SEGMENT_SKEW_SEGMENT_RAY_HPP_INCLUDED

#include "../ray_segment/ray_segment_skew_ray_segment.hpp"

inline bool skew(const Segment3& first, const Ray3& second){
    return skew(second, first);
}

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_RAY_RAY_SEGMENT_SKEW_SEGMENT_RAY_HPP_INCLUDED
