#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_RAY_RAY_SEGMENT_PARALLEL_SEGMENT_RAY_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_RAY_RAY_SEGMENT_PARALLEL_SEGMENT_RAY_HPP_INCLUDED

#include "../ray_segment/ray_segment_parallel_ray_segment.hpp"

inline bool parallel(const Segment3& first, const Ray3& second){
    return parallel(second, first);
}

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_PREDICATE_SEGMENT_RAY_RAY_SEGMENT_PARALLEL_SEGMENT_RAY_HPP_INCLUDED
