#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_CENTROID_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_CENTROID_HPP_INCLUDED

#include "../../point/tetrahedron/tetrahedron_centroid.hpp"
#include "../../point/triangle/triangle_centroid.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_CENTROID_HPP_INCLUDED
