#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_CONVEX_POLYHEDRON_INTERSECTION_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_CONVEX_POLYHEDRON_INTERSECTION_HPP_INCLUDED

#include "../../polyhedron/polyhedron_polyhedron/convex_polyhedron_intersection_default.hpp"
#include "../../polyhedron/polyhedron_polyhedron/convex_polyhedron_intersection_via_halfspaces.hpp"
#include "../../polyhedron/polyhedron_polyhedron_point/convex_polyhedron_intersection_with_interior_point.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_CONVEX_POLYHEDRON_INTERSECTION_HPP_INCLUDED
