#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_EXACT_ORIENT3D_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_EXACT_ORIENT3D_HPP_INCLUDED

#include "../../integer/scalar/exact_orient3d_integer_points.hpp"
#include "../../type/definition/integer_point3.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_EXACT_ORIENT3D_HPP_INCLUDED
