#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_GAUSSIAN_ELIMINATION_REAL_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_GAUSSIAN_ELIMINATION_REAL_HPP_INCLUDED

#include "../../result/scalar/gaussian_elimination_real_rref.hpp"
#include "../../scalar/scalar/solve_square_linear_system_real.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_GAUSSIAN_ELIMINATION_REAL_HPP_INCLUDED
