#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_LINE_PLANE_CLOSEST_POINTS_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_LINE_PLANE_CLOSEST_POINTS_HPP_INCLUDED

#include "../../point_set/line_plane/line_plane_closest_points_line_plane.hpp"
#include "../../point_set/plane_line/line_plane_closest_points_plane_line.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_LINE_PLANE_CLOSEST_POINTS_HPP_INCLUDED
