#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_PLANE_COORDINATE_SYSTEM_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_PLANE_COORDINATE_SYSTEM_HPP_INCLUDED

#include "../../type/definition/plane_coordinate_system3.hpp"
#include "../../result/plane/plane_coordinate_system_from_plane.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_PLANE_COORDINATE_SYSTEM_HPP_INCLUDED
