#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_POLYGON3_TRIANGULATION_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_POLYGON3_TRIANGULATION_HPP_INCLUDED

#include "../../index_set/polygon/polygon3_triangulation_indices.hpp"
#include "../../triangle/polygon/polygon3_triangulation_triangles.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_POLYGON3_TRIANGULATION_HPP_INCLUDED
