#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_PROJECTION_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_PROJECTION_HPP_INCLUDED

#include "../../point/line_point/line_point_projection.hpp"
#include "../../point/plane_point/plane_point_projection.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_PROJECTION_HPP_INCLUDED
