#ifndef CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_RAY_SEGMENT_CLOSEST_POINTS_HPP_INCLUDED
#define CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_RAY_SEGMENT_CLOSEST_POINTS_HPP_INCLUDED

#include "../../point_set/ray_segment/ray_segment_closest_points_ray_segment.hpp"
#include "../../point_set/segment_ray/ray_segment_closest_points_segment_ray.hpp"

#endif  // CPPLIB_SRC_ALGORITHM_GEOMETRY_3D_AGGREGATE_ALL_RAY_SEGMENT_CLOSEST_POINTS_HPP_INCLUDED
